### ISSUE TITLE
Should we use camelCase or hyphen-separated css classes?

### ISSUE THREAD

**Issue by rafaellyra** [Werkspot/idiomatic-css#1]
I think that as is hard to find a css code styleguide using camelCase, and most open source projects (font-icons, grids) use hyphens (`-`) we should follow the hyphens rule.
1. Our current css is camelCase (we can refactor just the code that we change or add)
2. It is more consistent when you are using pseudo-elements:

```
.myElement:first-child {
    ...
}

.my-element:first-child {
    ...
}
```

disclaimer: please don't hate me for it :(

**Comment by caseycs** [comment]
I like both, my only concern is - it should be consistent everywhere

**Comment by MarijnKoesen** [comment]
I think Rafael's arguments to use hyphens are  good. But mixing them as Ilya already mentioned is not a good idea. It will be a real mess...

I think we'll need to discuss if we want to change and how, e.g. if we start a new frontend based on the POC then maybe yes, otherwise probably no even though it might be better.

**Comment by rafaellyra** [comment]
@MarijnKoesen the POC was killed :( (but I still thinking that we should use '-'):

**Comment by MarijnKoesen** [comment]
Do you have an idea if and how we can migrate @rafaellyra ?

**Comment by rafaellyra** [comment]
I think that we should start to use `-` for all new css and update the `old` code that we touch, I also have more samples where we need to use `-` cause of third-party code:

icons:
`.icon-help-circled`

grid: (bootstrap based grid)
`.col-xs-1`

**Comment by prestes** [comment]
@MarijnKoesen If we would want to migrate to a new version, couldn't we just write a script to replace all camelCase classes to dash-separated?

We could start by creating a dictionary from the less files and applying only inside class tags in html.twig files.

**Comment by rafaellyra** [comment]
@prestes we also should care about javascript manipulating css classes too ;)

**Comment by prestes** [comment]
I don't really care about the specific code-style.

What I do care is that it’s already consistent since the beginning, therefore, I think we should fix it all if we decide to use a new standard, using some automation + some manual checks.

**Comment by MarijnKoesen** [comment]
As I mentioned before I agree above all that it should be consistent. So I don't like to update old code as we touch it, we should plan for it and do it all at once.

I think the dashes are a little more readable and also more consistent with css itself (`font-size`, `max-height` instead of `maxHeight` etc) so I'm fine to change to dashes (as well as more used, but that's not the best argument).
